name: "[v4-client-js] Lint, Build, & Test"
on: # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - 'v4-client-js/**'
  push:
    paths:
      - 'v4-client-js/**'
    branches:
      - main
      - "release/*"

jobs:
  CI:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./v4-client-js
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Cache Deno modules
        uses: actions/cache@v2
        with:
          path: ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Install dependencies
        run: deno cache --lock=deno.lock --lock-write deps.ts

      - name: Run lint
        run: deno lint

      - name: Run tests
        run: deno test --allow-net --allow-read
